### ISSUE TITLE
Twitter Acct

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/ok-data-website#1]
Twitter acct has been made (@okcdata). cc @waylonflinn

cc @the-simian the domain name is ok-data.... were you suggesting the group be called okdata / @okdata ?

uh so @waylonflinn / MDS do you all want to rename the twitter acct before the meeting? 

data ppl: you all aren't having food sponsored, right?

--

hope it all goes well! have a great time tonight!

**Comment by seejessicacode** [comment]
Looks like OKC Data Group is on hiatus indefinitely. https://twitter.com/okcdata

@amandaharlin Can you close this issue please?
